import mongoose from "mongoose";

const payoutSchema = new mongoose.Schema({
    user: { 

        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true,
        index: true
    },
    amount: {
        type: Number,
        required: true,
        min: 0.1// minimum payout amount is 0.1naira.
    },
    currency: {
        type: String,
        required: true,
        default: "NGN"// since we are in nigeria.
        upperCase: true
    },

    // Unique transfer code generated by your payment provider eg paystack, flutterwave, etc.
     paymentReference: {
         type: String,
         required: true,
         unique: true,
        trim: true
     },

     bankDetails: {
       bankCode: {type: String, required: true},
         accountNumber: {type: String, required: true},
            accountName: {type: String, required: true},
            bankName: {type: String, required: true}
     },
     satus: {
        type: String,
        enum: ["pending", "completed","processing","reversed", "failed"],
        default: "pending",
        index: true
     },
     //If bank transfer fails, store the reason code sent back by the banking network.
     failureReason: {
        type: String,
        default: null
     },
    } ,{
    timestamps: true// Tracks createdAt and updatedAt
});
 
const Payout = mongoose.model("Payout", payoutSchema);
export default Payout;